//
// This file generated by rdl 1.5.0. Do not modify!
//
package com.yahoo.athenz.zcs;

import com.yahoo.rdl.*;
import java.util.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

//
// ZCSHandler is the interface that the service implementation must implement
//
public interface ZCSHandler { 
    public void getSamlLogin(ResourceContext context, String url, GetSamlLoginResult result);
    public void getSamlLogout(ResourceContext context, String url, GetSamlLogoutResult result);
    public Status getStatus(ResourceContext context);
    public Schema getRdlSchema(ResourceContext context);
    public ResourceContext newResourceContext(HttpServletRequest request, HttpServletResponse response);
}
