//
// This file generated by rdl 1.5.0. Do not modify!
//

package com.yahoo.athenz.zcs;
import com.yahoo.rdl.*;

//
// SamlLogout - The representation for SAML logout message object
//
public class SamlLogout {
    public int code;
    public String message;

    public SamlLogout setCode(int code) {
        this.code = code;
        return this;
    }
    public int getCode() {
        return code;
    }
    public SamlLogout setMessage(String message) {
        this.message = message;
        return this;
    }
    public String getMessage() {
        return message;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != SamlLogout.class) {
                return false;
            }
            SamlLogout a = (SamlLogout) another;
            if (code != a.code) {
                return false;
            }
            if (message == null ? a.message != null : !message.equals(a.message)) {
                return false;
            }
        }
        return true;
    }
}
